"""Persisted, cluster-level identity governance.

MaterialMatch is evidence only.  This service is the single writer for new cluster
workflow state, so reviewed memberships are never regenerated by a page request.
"""
from collections import defaultdict
from datetime import datetime

from fastapi import HTTPException

from app.models.cpse import CPSE
from app.models.material import Material
from app.models.material_cluster import MaterialCluster
from app.models.material_cluster_member import MaterialClusterMember
from app.models.material_mapping import MaterialMapping
from app.models.material_match import MaterialMatch
from app.services.audit_service import write_audit
from app.services.conflict_resolution_service import propose_canonical, unresolved_critical_conflicts
from app.services.mapping_service import map_material
from app.services.national_code_service import create_national_material

IDENTITY_RELATIONS = {"EXACT", "NEAR_DUPLICATE"}
CLUSTER_STATUSES = {"PROPOSED", "UNDER_REVIEW", "READY_FOR_APPROVAL", "APPROVED", "REJECTED"}
ACTIVE_CLUSTER_STATUSES = CLUSTER_STATUSES - {"REJECTED"}


class UnionFind:
    def __init__(self): self.parent = {}
    def find(self, value):
        self.parent.setdefault(value, value)
        if self.parent[value] != value: self.parent[value] = self.find(self.parent[value])
        return self.parent[value]
    def union(self, a, b):
        a, b = self.find(a), self.find(b)
        if a != b: self.parent[max(a, b)] = min(a, b)


def _risk(materials, identity_edges, functional_count, mappings):
    proposal = propose_canonical(materials)
    critical = unresolved_critical_conflicts(proposal)
    families = {str(m.category or "").strip().upper() for m in materials if m.category}
    units = {str(m.unit or "").strip().upper() for m in materials if m.unit}
    national_ids = set(mappings.values())
    confidence = sum(e.final_score for e in identity_edges) / len(identity_edges) if identity_edges else 0
    missing = any(not (m.specifications or {}) for m in materials)
    high = bool(critical or functional_count or len(families) > 1 or len(national_ids) > 1)
    if high: return "HIGH", proposal, [*critical]
    if confidence >= .90 and len(units) <= 1 and not missing: return "LOW", proposal, []
    return "MEDIUM", proposal, []


def has_active_identity_overlap(db, material_ids, excluded_cluster_id=None):
    query = db.query(MaterialClusterMember.id).join(
        MaterialCluster, MaterialCluster.id == MaterialClusterMember.cluster_id
    ).filter(
        MaterialClusterMember.material_id.in_(material_ids),
        MaterialClusterMember.member_type == "IDENTITY",
        MaterialClusterMember.membership_status == "ACTIVE",
        MaterialCluster.status.in_(ACTIVE_CLUSTER_STATUSES),
    )
    if excluded_cluster_id is not None:
        query = query.filter(MaterialClusterMember.cluster_id != excluded_cluster_id)
    return query.first() is not None


def generate_proposed_clusters(db, actor_id=None):
    """Discover new identity components from unresolved evidence once per run.

    A component that already has a persisted cluster with the same active identity
    membership is left untouched, including when that cluster has human edits.
    """
    edges = db.query(MaterialMatch).filter(MaterialMatch.status == "PENDING").filter(
        MaterialMatch.classification.in_([*IDENTITY_RELATIONS, "FUNCTIONAL_EQUIVALENT"])).all()
    identity = UnionFind()
    for edge in edges:
        if edge.classification in IDENTITY_RELATIONS: identity.union(edge.material_a_id, edge.material_b_id)
    groups = defaultdict(set)
    for edge in edges:
        if edge.classification in IDENTITY_RELATIONS:
            groups[identity.find(edge.material_a_id)].update((edge.material_a_id, edge.material_b_id))
    created = []
    for member_ids in groups.values():
        if len(member_ids) < 2: continue
        # New AI evidence must never place a material in a second active identity
        # governance unit. Existing reviewed membership is the source of truth.
        if has_active_identity_overlap(db, member_ids):
            continue
        # Lock candidate rows then recheck, serializing competing generation
        # requests that discover the same AI component.
        db.query(Material).filter(Material.id.in_(member_ids)).with_for_update().all()
        if has_active_identity_overlap(db, member_ids):
            continue
        members_key = frozenset(member_ids)
        existing = db.query(MaterialCluster).filter(MaterialCluster.status != "REJECTED").all()
        duplicate = False
        for cluster in existing:
            active = {row.material_id for row in db.query(MaterialClusterMember).filter(
                MaterialClusterMember.cluster_id == cluster.id,
                MaterialClusterMember.member_type == "IDENTITY",
                MaterialClusterMember.membership_status == "ACTIVE").all()}
            if active == members_key: duplicate = True; break
        if duplicate: continue
        identity_edges = [e for e in edges if e.classification in IDENTITY_RELATIONS and e.material_a_id in member_ids and e.material_b_id in member_ids]
        functional_edges = [e for e in edges if e.classification == "FUNCTIONAL_EQUIVALENT" and (e.material_a_id in member_ids or e.material_b_id in member_ids)]
        functional_ids = {x for e in functional_edges for x in (e.material_a_id, e.material_b_id)} - set(member_ids)
        materials = db.query(Material).filter(Material.id.in_(member_ids)).all()
        mappings = dict(db.query(MaterialMapping.material_id, MaterialMapping.national_material_id).filter(MaterialMapping.material_id.in_(member_ids)).all())
        level, proposal, _ = _risk(materials, identity_edges, len(functional_edges), mappings)
        cluster = MaterialCluster(status="READY_FOR_APPROVAL" if level == "LOW" else "PROPOSED", created_by=actor_id,
            risk_level=level, canonical_material_id=proposal["source_material_ids"][0] if proposal["source_material_ids"] else None)
        db.add(cluster); db.flush(); cluster.cluster_code = f"C-{cluster.id:06d}"
        for material_id in member_ids:
            strongest = max((e for e in identity_edges if material_id in (e.material_a_id, e.material_b_id)), key=lambda e:e.final_score, default=None)
            db.add(MaterialClusterMember(cluster_id=cluster.id, material_id=material_id, member_type="IDENTITY", membership_status="ACTIVE",
                relationship_type=strongest.classification if strongest else "NEAR_DUPLICATE", ai_match_id=strongest.id if strongest else None,
                confidence=strongest.final_score if strongest else None, added_by=actor_id))
        for material_id in functional_ids:
            strongest = max((e for e in functional_edges if material_id in (e.material_a_id, e.material_b_id)), key=lambda e:e.final_score, default=None)
            db.add(MaterialClusterMember(cluster_id=cluster.id, material_id=material_id, member_type="FUNCTIONAL_ALTERNATIVE", membership_status="ACTIVE",
                relationship_type="FUNCTIONAL_EQUIVALENT", ai_match_id=strongest.id if strongest else None,
                confidence=strongest.final_score if strongest else None, added_by=actor_id))
        write_audit(db, "CLUSTER_GENERATED", "MaterialCluster", cluster.id, actor_id,
                    {"identity_member_ids": sorted(member_ids), "functional_member_ids": sorted(functional_ids), "risk_level": level}, commit=False)
        created.append(cluster)
    db.commit()
    return created


def _cluster_payload(db, cluster):
    rows = db.query(MaterialClusterMember).filter(MaterialClusterMember.cluster_id == cluster.id).all()
    ids = [r.material_id for r in rows]
    materials = {m.id:m for m in db.query(Material).filter(Material.id.in_(ids)).all()} if ids else {}
    cpses = {c.id:c.code for c in db.query(CPSE).filter(CPSE.id.in_({m.cpse_id for m in materials.values()})).all()} if materials else {}
    mappings = dict(db.query(MaterialMapping.material_id, MaterialMapping.national_material_id).filter(MaterialMapping.material_id.in_(ids)).all()) if ids else {}
    identity = [r for r in rows if r.member_type == "IDENTITY" and r.membership_status == "ACTIVE"]
    identity_materials = [materials[r.material_id] for r in identity if r.material_id in materials]
    evidence = db.query(MaterialMatch).filter(MaterialMatch.id.in_([r.ai_match_id for r in rows if r.ai_match_id])).all()
    level, proposal, critical = _risk(identity_materials, evidence, len([r for r in rows if r.member_type == "FUNCTIONAL_ALTERNATIVE" and r.membership_status == "ACTIVE"]), {r.material_id:mappings[r.material_id] for r in identity if r.material_id in mappings}) if identity_materials else ("HIGH", propose_canonical([]), [])
    def data(row):
        material = materials.get(row.material_id)
        return {"material_id": row.material_id, "member_type": row.member_type, "membership_status": row.membership_status,
                "relationship_type": row.relationship_type, "confidence": row.confidence, "ai_match_id": row.ai_match_id,
                "removal_reason": row.removal_reason, "material_code": material.material_code if material else None,
                "description": material.description if material else None, "cpse": cpses.get(material.cpse_id) if material else None,
                "specifications": material.specifications if material else {}, "mapped_national_material_id": mappings.get(row.material_id)}
    mapped = {mappings[r.material_id] for r in identity if r.material_id in mappings}
    state = "CONFLICT" if len(mapped) > 1 else "EXTEND" if mapped else "CREATE"
    return {"id":cluster.id, "cluster_id":cluster.id, "cluster_code":cluster.cluster_code or f"C-{cluster.id:06d}", "status":cluster.status,
            "risk_level":cluster.risk_level or level, "canonical_material_id":cluster.canonical_material_id, "national_material_id":cluster.national_material_id,
            "proposed_canonical_description":proposal["description"], "canonical_proposal":proposal, "identity_members":[data(r) for r in rows if r.member_type == "IDENTITY" and r.membership_status == "ACTIVE"],
            "functional_alternatives":[data(r) for r in rows if r.member_type == "FUNCTIONAL_ALTERNATIVE" and r.membership_status == "ACTIVE"],
            "removed_members":[data(r) for r in rows if r.membership_status == "REMOVED"], "conflicts":critical or proposal.get("conflicts", []),
            "mapping_destination":{"state":state, "national_material_id":next(iter(mapped), None)}, "review_comment":cluster.review_comment,
            "created_at":cluster.created_at, "reviewed_at":cluster.reviewed_at, "submitted_at":cluster.submitted_at, "approved_at":cluster.approved_at}


def get_clusters(db, status=None, page=1, limit=25):
    query = db.query(MaterialCluster)
    if status: query = query.filter(MaterialCluster.status == status)
    total = query.count(); rows = query.order_by(MaterialCluster.updated_at.desc()).offset((page-1)*limit).limit(limit).all()
    return {"items":[_cluster_payload(db, row) for row in rows], "page":page, "limit":limit, "total":total, "pages":max(1, (total + limit - 1)//limit)}


def submit_cluster(db, cluster, actor_id, comment=None):
    if cluster.status not in {"PROPOSED", "UNDER_REVIEW"}: raise HTTPException(409, "Only proposed or reviewed clusters can be submitted")
    payload = _cluster_payload(db, cluster)
    if not payload["identity_members"]: raise HTTPException(409, "At least one active identity member is required")
    if payload["risk_level"] == "HIGH" and payload["conflicts"]: raise HTTPException(409, {"message":"Resolve critical engineering conflicts before submission", "conflicts":payload["conflicts"]})
    if payload["mapping_destination"]["state"] == "CONFLICT": raise HTTPException(409, "Mapping conflict requires explicit governance resolution")
    cluster.status="READY_FOR_APPROVAL"; cluster.submitted_by=actor_id; cluster.submitted_at=datetime.utcnow(); cluster.review_comment=comment; cluster.version += 1
    write_audit(db,"CLUSTER_SUBMITTED","MaterialCluster",cluster.id,actor_id,{"comment":comment},commit=False); db.commit()
    return _cluster_payload(db, cluster)


def approve_cluster(db, cluster_id, actor_id, comment=None):
    cluster = db.query(MaterialCluster).filter(MaterialCluster.id == cluster_id).with_for_update().first()
    if not cluster: raise HTTPException(404, "Cluster not found")
    if cluster.status == "APPROVED": return {"status":"ALREADY_APPROVED", "cluster":_cluster_payload(db, cluster)}
    if cluster.status != "READY_FOR_APPROVAL": raise HTTPException(409, "Cluster must be READY_FOR_APPROVAL")
    payload = _cluster_payload(db, cluster)
    # HIGH means the reviewer must perform detailed review; it is not a
    # permanent approval ban.  A submitted high-risk cluster can be approved
    # once its active identity set has no unresolved engineering conflict.
    if payload["conflicts"]: raise HTTPException(409, "Cluster has unresolved engineering conflicts")
    if payload["mapping_destination"]["state"] == "CONFLICT": raise HTTPException(409, "Cluster moved to mapping conflict")
    members = payload["identity_members"]
    if not members: raise HTTPException(409, "No active identity members")
    material_ids = [r["material_id"] for r in members]
    materials = db.query(Material).filter(Material.id.in_(material_ids)).with_for_update().all()
    mapped = {r["mapped_national_material_id"] for r in members if r["mapped_national_material_id"]}
    proposal = propose_canonical(materials)
    try:
        if mapped:
            national_id = next(iter(mapped))
        else:
            national, _ = create_national_material(db, proposal["description"], proposal["category"], proposal["unit"], proposal["specifications"], proposal.get("subcategory"), {"cluster_id":cluster.id, "source_material_ids":material_ids}, actor_id=actor_id, commit=False, return_created=True)
            national_id = national.id
        for material_id in material_ids: map_material(db, material_id, national_id, "CLUSTER_APPROVED", actor_id)
        cluster.status="APPROVED"; cluster.national_material_id=national_id; cluster.approved_by=actor_id; cluster.approved_at=datetime.utcnow(); cluster.approval_comment=comment; cluster.version += 1
        db.query(MaterialMatch).filter(MaterialMatch.status == "PENDING", MaterialMatch.material_a_id.in_(material_ids), MaterialMatch.material_b_id.in_(material_ids), MaterialMatch.classification.in_(IDENTITY_RELATIONS)).update({MaterialMatch.status:"RESOLVED"}, synchronize_session=False)
        write_audit(db,"CLUSTER_APPROVED","MaterialCluster",cluster.id,actor_id,{"national_material_id":national_id,"identity_member_ids":material_ids},commit=False)
        db.commit()
    except Exception:
        db.rollback(); raise
    return {"status":"APPROVED", "cluster":_cluster_payload(db, cluster)}
