import { useEffect, useMemo, useState } from 'react';
import { Boxes, Edit3, PackagePlus, RefreshCw, Search, Warehouse } from 'lucide-react';
import { inventoryApi } from '../services/inventoryApi';
import { materialApi } from '../services/materialApi';
import { cpseApi } from '../services/cpseApi';
import { Button } from '../components/common/Button';
import { Modal } from '../components/common/Modal';
import { useAuth } from '../hooks/useAuth';
import { hasPermission } from '../utils/permissions';

const blank=(cpse='')=>({cpse_id:cpse,material_id:'',warehouse:'',available_quantity:'',reserved_quantity:'0',uom:'EA',unit_cost:''});
const qty=value=>Number(value||0);

export const Inventory=()=>{
  const {user}=useAuth(); const canWrite=hasPermission(user,'inventory.write'); const canChooseCpse=hasPermission(user,'*');
  const [rows,setRows]=useState([]),[materials,setMaterials]=useState([]),[cpses,setCpses]=useState([]),[query,setQuery]=useState(''),[filterCpse,setFilterCpse]=useState('');
  const [form,setForm]=useState(blank(user?.cpse_id||'')),[editingId,setEditingId]=useState(null),[modal,setModal]=useState(false),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const load=async()=>{setLoading(true);try{const [i,m,c]=await Promise.all([inventoryApi.getAll(),materialApi.getMaterials(),cpseApi.getAll()]);setRows(i.data||[]);setMaterials(m.data||[]);setCpses(c.data||[]);setError('')}catch(e){setError(e?.response?.data?.detail||e.message||'Unable to load inventory.')}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const materialById=useMemo(()=>Object.fromEntries(materials.map(x=>[x.id,x])),[materials]); const cpseById=useMemo(()=>Object.fromEntries(cpses.map(x=>[x.id,x])),[cpses]);
  const availableMaterials=materials.filter(x=>!form.cpse_id||x.cpseId===Number(form.cpse_id)); const stocked=useMemo(()=>new Set(rows.map(x=>x.material_id)),[rows]);
  const display=useMemo(()=>[...rows,...materials.filter(m=>!stocked.has(m.id)).map(m=>({id:`not-stocked-${m.id}`,material_id:m.id,cpse_id:m.cpseId,warehouse:'',available_quantity:0,reserved_quantity:0,uom:m.uom,not_stocked:true}))],[rows,materials,stocked]);
  const filtered=display.filter(r=>{const m=materialById[r.material_id],c=cpseById[r.cpse_id],text=`${c?.code||''} ${m?.code||''} ${m?.nationalCode||''} ${m?.description||''} ${r.warehouse||''}`.toLowerCase();return(!filterCpse||String(r.cpse_id)===filterCpse)&&(!query.trim()||text.includes(query.trim().toLowerCase()))});
  const totals=filtered.filter(x=>!x.not_stocked).reduce((a,x)=>({available:a.available+qty(x.available_quantity),reserved:a.reserved+qty(x.reserved_quantity)}),{available:0,reserved:0});
  const close=()=>{setModal(false);setEditingId(null);setForm(blank(user?.cpse_id||''))};
  const openEdit=row=>{setEditingId(row.id);setForm({cpse_id:String(row.cpse_id),material_id:String(row.material_id),warehouse:row.warehouse,available_quantity:String(row.available_quantity),reserved_quantity:String(row.reserved_quantity),uom:row.uom,unit_cost:row.unit_cost==null?'':String(row.unit_cost)});setModal(true)};
  const openAdd=row=>{setEditingId(null);setForm({...blank(String(row.cpse_id)),material_id:String(row.material_id),uom:row.uom||materialById[row.material_id]?.uom||'EA'});setModal(true)};
  const save=async event=>{event?.preventDefault();const available=qty(form.available_quantity),reserved=qty(form.reserved_quantity);if(!form.cpse_id||!form.material_id||!form.warehouse.trim()||!form.uom.trim())return setError('Select CPSE and material, then enter warehouse and unit of measure.');if(available<0||reserved<0||reserved>available)return setError('Available stock must be non-negative and cannot be lower than reserved stock.');setSaving(true);try{const payload={...form,cpse_id:Number(form.cpse_id),material_id:Number(form.material_id),warehouse:form.warehouse.trim(),available_quantity:available,reserved_quantity:reserved,uom:form.uom.trim().toUpperCase(),unit_cost:form.unit_cost===''?null:qty(form.unit_cost)};editingId?await inventoryApi.update(editingId,payload):await inventoryApi.create(payload);close();await load()}catch(e){setError(e?.response?.data?.detail||e.message||'Unable to save stock.')}finally{setSaving(false)}};
  const labelClass='flex flex-col gap-1.5 text-xs font-semibold text-slate-700';
  const controlClass='w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm font-medium text-slate-800 outline-none transition placeholder:text-slate-400 focus:border-blue-500 focus:ring-2 focus:ring-blue-100 disabled:cursor-not-allowed disabled:border-slate-200 disabled:bg-slate-100 disabled:text-slate-500';
  const fields=editingId?<><label className={labelClass}>CPSE<input className={controlClass} disabled value={cpseById[Number(form.cpse_id)]?.code||''}/></label><label className={labelClass}>Material<input className={controlClass} disabled value={materialById[Number(form.material_id)]?.code||''}/></label></>:<><label className={labelClass}>CPSE<select className={controlClass} required value={form.cpse_id} disabled={!canChooseCpse} onChange={e=>setForm({...form,cpse_id:e.target.value,material_id:''})}><option value="">Select CPSE</option>{cpses.map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</select></label><label className={labelClass}>Material<select className={controlClass} required value={form.material_id} onChange={e=>{const m=materialById[e.target.value];setForm({...form,material_id:e.target.value,uom:m?.uom||form.uom})}}><option value="">Select material</option>{availableMaterials.map(x=><option key={x.id} value={x.id}>{x.code} — {x.description}</option>)}</select></label></>;
  return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-bold">Cross-CPSE Inventory</h2><p className="text-xs text-slate-500">Track usable stock, reservations, and reusable material availability before procurement.</p></div><Button variant="secondary" size="sm" icon={RefreshCw} onClick={load} loading={loading}>Refresh</Button></div>{error&&<div className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-xs text-rose-700">{error}</div>}
    <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border bg-white p-4"><p className="text-[11px] font-bold uppercase text-slate-500">CPSE products</p><p className="mt-1 text-2xl font-bold">{filtered.length}</p></div><div className="rounded-xl border bg-white p-4"><p className="text-[11px] font-bold uppercase text-slate-500">Available stock</p><p className="mt-1 text-2xl font-bold text-blue-700">{totals.available.toLocaleString()}</p></div><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="text-[11px] font-bold uppercase text-emerald-700">Effective available</p><p className="mt-1 text-2xl font-bold text-emerald-700">{Math.max(totals.available-totals.reserved,0).toLocaleString()}</p><p className="text-[11px] text-emerald-700">{totals.reserved.toLocaleString()} reserved</p></div></div>
    <section className="overflow-hidden rounded-xl border bg-white">
      <div className="flex flex-col gap-3 border-b bg-slate-50 p-4 sm:flex-row">
        <div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search material, CPSE, or warehouse" className="w-full rounded-lg border bg-white py-2 pl-9 pr-3 text-xs" /></div>
        <select value={filterCpse} onChange={e => setFilterCpse(e.target.value)} className="rounded-lg border bg-white px-3 py-2 text-xs"><option value="">All CPSEs</option>{cpses.map(x => <option key={x.id} value={x.id}>{x.code}</option>)}</select>
      </div>
      <div className="grid gap-4 p-4 lg:grid-cols-2">
        {filtered.map(row => {
          const material = materialById[row.material_id];
          const cpse = cpseById[row.cpse_id];
          const effective = Math.max(qty(row.available_quantity) - qty(row.reserved_quantity), 0);
          const imageUrl = row.primary_image_url || material?.primaryImageUrl;
          return <article key={row.id} className={`rounded-xl border bg-white p-4 shadow-sm ${row.not_stocked ? 'border-dashed' : ''}`}>
            <div className="flex items-start justify-between gap-3"><div className="min-w-0 flex-1"><span className="rounded-full bg-blue-50 px-2 py-1 text-[10px] font-bold text-blue-700">{cpse?.code || `CPSE #${row.cpse_id}`}</span>{row.not_stocked && <span className="ml-2 rounded-full bg-amber-50 px-2 py-1 text-[10px] font-bold text-amber-700">Not stocked</span>}<div className="mt-3 font-mono text-sm font-bold text-slate-900">{material?.code || `Material #${row.material_id}`}</div>{material?.nationalCode && <div className="mt-1 font-mono text-[11px] font-semibold text-violet-700">National Code: {material.nationalCode}</div>}</div>{imageUrl && <img src={imageUrl} alt={`${material?.description || 'Material'} reference`} className="h-28 w-28 shrink-0 rounded-lg border border-slate-200 bg-slate-50 object-contain p-1" onError={event => { event.currentTarget.style.display = 'none'; }} />}{canWrite && (row.not_stocked ? <button type="button" onClick={() => openAdd(row)} className="inline-flex shrink-0 items-center gap-1 text-xs font-semibold text-blue-700 hover:text-blue-900"><PackagePlus className="h-3.5 w-3.5" />Add stock</button> : <button type="button" onClick={() => openEdit(row)} className="inline-flex shrink-0 items-center gap-1 text-xs font-semibold text-blue-700 hover:text-blue-900"><Edit3 className="h-3.5 w-3.5" />Edit</button>)}</div>
            <p className="mt-2 min-h-10 text-sm font-medium text-slate-700">{material?.description || 'Material description is unavailable.'}</p>
            <div className="mt-3 flex items-center gap-1 text-xs text-slate-500"><Warehouse className="h-3.5 w-3.5" />{row.warehouse || 'No warehouse or stock record registered'}</div>
            <dl className="mt-4 grid gap-x-4 gap-y-3 border-y py-3 text-xs sm:grid-cols-2">
              <div><dt className="text-slate-500">Category</dt><dd className="mt-1 font-medium text-slate-800">{material?.category || 'Not specified'}</dd></div>
              <div><dt className="text-slate-500">Unit of measure</dt><dd className="mt-1 font-medium text-slate-800">{row.uom || material?.uom || 'Not specified'}</dd></div>
              <div><dt className="text-slate-500">Manufacturer</dt><dd className="mt-1 font-medium text-slate-800">{material?.manufacturer || 'Not specified'}</dd></div>
              <div><dt className="text-slate-500">Model / part number</dt><dd className="mt-1 font-medium text-slate-800">{material?.model || 'Not specified'}</dd></div>
              <div><dt className="text-slate-500">Record source</dt><dd className="mt-1 font-medium text-slate-800">{material?.source || 'Manual'}</dd></div>
              <div><dt className="text-slate-500">Material status</dt><dd className="mt-1 font-medium text-slate-800">{material?.status || 'ACTIVE'}</dd></div>
            </dl>
            <div className="mt-3 rounded-lg bg-slate-50 p-3 text-xs"><div className="font-semibold text-slate-700">Technical specification</div><p className="mt-1 whitespace-pre-wrap text-slate-600">{material?.specification || 'No technical specification was registered for this product.'}</p></div>
            <div className="mt-4 grid grid-cols-3 divide-x rounded-lg border bg-slate-50 text-center text-xs"><div className="p-3"><div className="text-slate-500">Available</div><strong className="mt-1 block text-blue-700">{qty(row.available_quantity).toLocaleString()} {row.uom}</strong></div><div className="p-3"><div className="text-slate-500">Reserved</div><strong className="mt-1 block text-amber-700">{qty(row.reserved_quantity).toLocaleString()} {row.uom}</strong></div><div className="p-3"><div className="text-slate-500">Ready to use</div><strong className="mt-1 block text-emerald-700">{effective.toLocaleString()} {row.uom}</strong></div></div>
          </article>;
        })}
      </div>
      {!loading && !filtered.length && <div className="p-10 text-center text-slate-400"><Boxes className="mx-auto h-8 w-8" /><p className="mt-2 text-sm font-semibold">No inventory records found</p></div>}
    </section>
    <Modal open={modal} onClose={()=>!saving&&close()} title={editingId?'Edit stock record':'Add stock record'} subtitle={editingId?'Update stock quantities without changing source identity.':'Create a stock record for this CPSE material.'} maxWidth="max-w-2xl" actions={<><Button size="sm" variant="ghost" disabled={saving} onClick={close}>Cancel</Button><Button size="sm" variant="primary" icon={editingId?Edit3:PackagePlus} loading={saving} onClick={save}>{editingId?'Save changes':'Add stock'}</Button></>}><form onSubmit={save} className="grid gap-5 sm:grid-cols-2"><div className="contents">{fields}</div><label className={`${labelClass} sm:col-span-2`}>Warehouse / depot<input className={controlClass} required value={form.warehouse} onChange={e=>setForm({...form,warehouse:e.target.value})}/></label><label className={labelClass}>Available quantity<input className={controlClass} required min="0" step="any" type="number" value={form.available_quantity} onChange={e=>setForm({...form,available_quantity:e.target.value})}/></label><label className={labelClass}>Reserved quantity<input className={controlClass} required min="0" step="any" type="number" value={form.reserved_quantity} onChange={e=>setForm({...form,reserved_quantity:e.target.value})}/></label><label className={labelClass}>Unit of measure<input className={controlClass} required value={form.uom} onChange={e=>setForm({...form,uom:e.target.value})}/></label></form></Modal>
  </div>;
};
