"""
src/fuzzy_score.py
--------------------
Wraps RapidFuzz to provide the fuzzy text-similarity signal -- the 20%
component of the hybrid score:

    final_score = 0.4 * semantic + 0.4 * attribute_match + 0.2 * fuzzy

Why we need this alongside semantic similarity: embeddings are great at
catching MEANING (hex vs hexagonal), but can sometimes be fooled by
short technical strings where a small character difference matters a lot
(e.g. "M16" vs "M18" might still embed as fairly similar since both are
short bolt-size tokens). Fuzzy string matching catches exact character-level
differences that embeddings can under-weight, so combining both signals
makes the overall score more robust than either alone.

Run this file directly to see it applied to your dataset:
    python src/fuzzy_score.py
"""

from rapidfuzz import fuzz

from normalize import normalize


def fuzzy_score(text_a: str, text_b: str) -> float:
    """
    Return a 0.0-1.0 fuzzy similarity score between two ALREADY-NORMALIZED
    strings (call normalize() on raw text first).

    Uses RapidFuzz's token_sort_ratio, which:
      - splits both strings into words (tokens)
      - sorts the tokens alphabetically
      - compares the sorted, joined strings

    This makes it insensitive to WORD ORDER, which matters a lot here --
    "HEXAGONAL BOLT M16" and "BOLT HEXAGONAL M16" should score identically
    even though the words are in a different order. A plain character-by-
    character comparison would incorrectly penalize that.

    RapidFuzz returns 0-100; we divide by 100 to match the 0.0-1.0 scale
    used by the other two signals (semantic similarity, attribute match).
    """
    if not text_a or not text_b:
        return 0.0
    return fuzz.token_sort_ratio(text_a, text_b) / 100.0


# ---------------------------------------------------------------------------
# Standalone test -- run this file directly to see fuzzy scoring in action
# on the synthetic dataset generated by data/make_dataset.py
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import csv
    import os
    from itertools import combinations

    print("=== fuzzy_score() demo on hardcoded examples ===\n")
    examples = [
        "HEX BOLT M16 X 50 MM SS304",
        "Hexagonal Bolt M16*50 Stainless Steel 304",
        "SS 304 HEX HEAD BOLT M16 X 50",   # word order shuffled
        "HEX BOLT M20 X 75 MM SS304",       # genuinely different size
    ]
    normalized = [normalize(e) for e in examples]

    for i, j in combinations(range(len(examples)), 2):
        score = fuzzy_score(normalized[i], normalized[j])
        print(f"  [{i}] {examples[i]}")
        print(f"  [{j}] {examples[j]}")
        print(f"       fuzzy_score = {score:.2f}\n")

    # Apply to the real dataset if it exists -- compare the first record
    # against every other record to see which ones score highest.
    data_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "data",
        "synthetic_materials.csv",
    )
    if os.path.exists(data_path):
        print("=== fuzzy_score() applied to your synthetic dataset ===")
        with open(data_path, newline="", encoding="utf-8") as f:
            rows = list(csv.DictReader(f))

        target = rows[0]
        target_norm = normalize(target["original_description"])
        print(f"\nComparing everything against:")
        print(f"  [{target['cpse']}] {target['original_description']}\n")

        scored = []
        for r in rows[1:]:
            norm = normalize(r["original_description"])
            score = fuzzy_score(target_norm, norm)
            scored.append((score, r))

        scored.sort(key=lambda x: x[0], reverse=True)
        for score, r in scored[:8]:
            print(f"  {score:.2f}  [{r['cpse']}] {r['original_description']}")
        print(f"\n(showing top 8 of {len(scored)} comparisons)")
    else:
        print(f"No dataset found at {data_path} -- run data/make_dataset.py first.")