"""
src/normalize.py
------------------
Cleans and standardizes raw material descriptions BEFORE any matching
happens. This is step 1 of the pipeline:

    raw description -> normalize() -> clean description -> (attribute extraction, embeddings, fuzzy)

Why this matters: "HEX BOLT M16 X 50 MM SS304" and
"Hexagonal Bolt M16*50 Stainless Steel 304" describe the exact same item,
but a computer sees them as totally different strings. Normalizing brings
both descriptions closer together in wording BEFORE we even get to the
smarter (and more expensive) semantic/fuzzy comparisons.

Run this file directly to see it working on your synthetic dataset:
    python src/normalize.py
"""

import re


# ---------------------------------------------------------------------------
# Domain dictionary: abbreviation -> full form
# Add to this as you encounter more variations in your dataset / real data.
# Keys should be UPPERCASE; matching is done on uppercased text.
# ---------------------------------------------------------------------------
ABBREVIATIONS = {
    "HEX": "HEXAGONAL",
    "SS": "STAINLESS STEEL",
    "MS": "MILD STEEL",
    "CS": "CARBON STEEL",
    "GI": "GALVANIZED IRON",
    "DIA": "DIAMETER",
    "NOS": "NUMBERS",
    "PC": "PIECE",
    "PCS": "PIECES",
    "QTY": "QUANTITY",
    "HD": "HEAD",
    "SQ": "SQUARE",
    "RD": "ROUND",
    "GR": "GRADE",
    "THK": "THICK",
    "APPROX": "APPROXIMATELY",
    "TRNSFRMR": "TRANSFORMER",
    "VLV": "VALVE",
}

TRANSLATIONS = {
    "इलेक्ट्रिक मोटर": "ELECTRIC MOTOR",
    "किलोवाट": "KW",
}

# Word-boundary regex for each abbreviation, built once at import time.
# \b ensures we don't turn "SSTAR" into "STAINLESS STEELTAR" etc.
_ABBREV_PATTERNS = [
    (re.compile(rf"\b{re.escape(short)}\b"), full)
    for short, full in ABBREVIATIONS.items()
]


def normalize(text: str) -> str:
    """
    Normalize a raw material description into a standard form.

    Steps:
      1. Uppercase everything (case shouldn't affect matching)
      2. Standardize dimension separators: '*' and lowercase 'x' -> 'X'
         so "M16*50" and "M16 x 50" both become "M16 X 50"
      3. Ensure a space between a number and a unit, e.g. "50MM" -> "50 MM"
      4. Collapse multiple spaces into one, strip leading/trailing whitespace
      5. Expand known abbreviations (HEX -> HEXAGONAL, SS -> STAINLESS STEEL...)
      6. Remove stray punctuation that doesn't carry meaning (commas, extra dashes)

    Returns the cleaned, uppercase, expanded description.
    """
    if not text:
        return ""

    t = text.upper()

    # Small, explicit multilingual engineering dictionary. Unknown text is
    # preserved for the embedding model instead of being guessed or discarded.
    for source, target in TRANSLATIONS.items():
        t = t.replace(source, target)

    # Standardize dimension "x" separators: "M16*50" / "M16x50" / "M16 X 50" -> "M16 X 50"
    # Only treat x/X/* as a separator when it sits BETWEEN two digits (ignoring
    # any spaces around it) -- this avoids matching the "X" inside words like "HEX".
    t = re.sub(r"(\d)\s*[xX*]\s*(\d)", r"\1 X \2", t)

    # Insert a space between digits and letters glued together, e.g. "50MM" -> "50 MM"
    t = re.sub(r"(\d)([A-Z])", r"\1 \2", t)

    # Insert a space between letters and a following digit, e.g. "SS304" -> "SS 304"
    # BUT skip single-letter metric/thread prefixes like "M16", "G20", "R10" --
    # only split when the letter is itself preceded by another letter
    # (i.e. part of a multi-letter code such as SS, MS, GR).
    t = re.sub(r"(?<=[A-Z])([A-Z])(\d)", r"\1 \2", t)

    # Remove commas and collapse repeated dashes/hyphens used as separators
    t = t.replace(",", " ")
    t = re.sub(r"-{1,}", " ", t)

    # Collapse multiple spaces
    t = re.sub(r"\s+", " ", t).strip()

    # Expand abbreviations (word-boundary safe)
    for pattern, full in _ABBREV_PATTERNS:
        t = pattern.sub(full, t)

    # Canonicalize common standards and imperial dimensions. Converting to a
    # single physical unit prevents 1 INCH and 25.4 MM from looking different.
    t = re.sub(r"\bAPI\s*(\d)\s*([A-Z])\b", r"API \1\2", t)

    def inches_to_mm(match):
        millimetres = float(match.group(1)) * 25.4
        value = f"{millimetres:.3f}".rstrip("0").rstrip(".")
        return f"{value} MM"

    t = re.sub(r"\b(\d+(?:\.\d+)?)\s*(?:INCHES|INCH|IN)\b", inches_to_mm, t)

    # Final whitespace cleanup after expansion (expansions can introduce
    # multi-word replacements that need re-collapsing)
    t = re.sub(r"\s+", " ", t).strip()

    return t


# ---------------------------------------------------------------------------
# Standalone test — run this file directly to see normalization in action
# on the synthetic dataset generated by data/make_dataset.py
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import csv
    import os

    data_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "data",
        "synthetic_materials.csv",
    )

    print("=== normalize() demo on hardcoded examples ===\n")
    examples = [
        "HEX BOLT M16 X 50 MM SS304",
        "Hexagonal Bolt M16*50 Stainless Steel 304",
        "SS 304 HEX HEAD BOLT M16 X 50",
        "HEX HEAD BOLT M16 50MM SS304",
    ]
    for e in examples:
        print(f"  RAW:  {e}")
        print(f"  NORM: {normalize(e)}\n")

    if os.path.exists(data_path):
        print("=== normalize() applied to your synthetic dataset ===\n")
        with open(data_path, newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            rows = list(reader)
        for r in rows[:10]:  # just show the first 10 so output isn't huge
            print(f"  [{r['cpse']}] {r['original_description']}")
            print(f"       -> {normalize(r['original_description'])}\n")
        print(f"(showing first 10 of {len(rows)} rows)")
    else:
        print(f"No dataset found at {data_path} — run data/make_dataset.py first.")
